
package ru.kravchenko.tm.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-17T01:34:13.197+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "UserNotFoundException", targetNamespace = "http://endpoint.tm.kravchenko.ru/")
public class UserNotFoundException_Exception extends Exception {

    private ru.kravchenko.tm.endpoint.UserNotFoundException userNotFoundException;

    public UserNotFoundException_Exception() {
        super();
    }

    public UserNotFoundException_Exception(String message) {
        super(message);
    }

    public UserNotFoundException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UserNotFoundException_Exception(String message, ru.kravchenko.tm.endpoint.UserNotFoundException userNotFoundException) {
        super(message);
        this.userNotFoundException = userNotFoundException;
    }

    public UserNotFoundException_Exception(String message, ru.kravchenko.tm.endpoint.UserNotFoundException userNotFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.userNotFoundException = userNotFoundException;
    }

    public ru.kravchenko.tm.endpoint.UserNotFoundException getFaultInfo() {
        return this.userNotFoundException;
    }
}
