package ru.kravchenko.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-17T01:34:13.444+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.kravchenko.ru/", name = "UserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tm.kravchenko.ru/UserEndpoint/authorizationRequest", output = "http://endpoint.tm.kravchenko.ru/UserEndpoint/authorizationResponse")
    @RequestWrapper(localName = "authorization", targetNamespace = "http://endpoint.tm.kravchenko.ru/", className = "ru.kravchenko.tm.endpoint.Authorization")
    @ResponseWrapper(localName = "authorizationResponse", targetNamespace = "http://endpoint.tm.kravchenko.ru/", className = "ru.kravchenko.tm.endpoint.AuthorizationResponse")
    public void authorization(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.kravchenko.ru/UserEndpoint/createUserRequest", output = "http://endpoint.tm.kravchenko.ru/UserEndpoint/createUserResponse", fault = {@FaultAction(className = UserLoginBusyException_Exception.class, value = "http://endpoint.tm.kravchenko.ru/UserEndpoint/createUser/Fault/UserLoginBusyException")})
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint.tm.kravchenko.ru/", className = "ru.kravchenko.tm.endpoint.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint.tm.kravchenko.ru/", className = "ru.kravchenko.tm.endpoint.CreateUserResponse")
    public void createUser(
        @WebParam(name = "login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws UserLoginBusyException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.tm.kravchenko.ru/UserEndpoint/logoutRequest", output = "http://endpoint.tm.kravchenko.ru/UserEndpoint/logoutResponse", fault = {@FaultAction(className = SessionNotFoundException_Exception.class, value = "http://endpoint.tm.kravchenko.ru/UserEndpoint/logout/Fault/SessionNotFoundException")})
    @RequestWrapper(localName = "logout", targetNamespace = "http://endpoint.tm.kravchenko.ru/", className = "ru.kravchenko.tm.endpoint.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://endpoint.tm.kravchenko.ru/", className = "ru.kravchenko.tm.endpoint.LogoutResponse")
    public void logout(
        @WebParam(name = "session", targetNamespace = "")
        ru.kravchenko.tm.endpoint.Session session
    ) throws SessionNotFoundException_Exception;
}
